# Generated by Django 4.1.5 on 2023-01-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(default='location', max_length=200)),
                ('type', models.CharField(max_length=100)),
                ('liveNumber', models.PositiveSmallIntegerField()),
                ('estimateNumber', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
