# Generated by Django 4.1.6 on 2023-02-03 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_building_location_building_lat_building_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='estimateNumber',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='building',
            name='liveNumber',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
