# Generated by Django 4.1.6 on 2023-02-03 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_emergencymodepollresults'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmergencyModePollResults',
            new_name='EmergencyModePollResult',
        ),
    ]
