# Generated by Django 4.1.6 on 2023-02-03 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_rename_emergencymodepollresults_emergencymodepollresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencymodepollresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
