# Generated by Django 4.1.6 on 2023-02-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_alter_emergencymodepollresult_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='lat',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='building',
            name='long',
            field=models.DecimalField(decimal_places=10, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='emergencymodepollresult',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='emergencymodepollresult',
            name='long',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=14, null=True),
        ),
    ]
