# Generated by Django 4.1.6 on 2023-02-16 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_rename_count_wifidatacounts_devicecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wifidatacounts',
            name='created_at',
        ),
        migrations.AddField(
            model_name='wifidatacounts',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
