# Generated by Django 4.1.6 on 2023-02-16 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_remove_wifidatacounts_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='liveNumber',
            new_name='deviceCount',
        ),
        migrations.AddField(
            model_name='building',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='WifiDataCounts',
        ),
    ]
