# Generated by Django 4.1.6 on 2023-02-22 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_rename_livenumber_building_devicecount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='building',
            old_name='modified_at',
            new_name='device_modified_at',
        ),
        migrations.AddField(
            model_name='building',
            name='estimate_modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='building',
            name='floorPlanCapacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='registrarCapacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='building',
            name='traffic',
            field=models.CharField(choices=[('High', 'High'), ('Low', 'Low')], default='High', max_length=4),
            preserve_default=False,
        ),
    ]
