# Generated by Django 4.1.6 on 2023-02-22 21:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0019_alter_building_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='id',
        ),
        migrations.AlterField(
            model_name='building',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
