# Generated by Django 4.1.6 on 2023-02-23 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_alter_building_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='poly',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
