# Generated by Django 4.1.5 on 2023-02-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_alter_emergencymodepollresult_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyModeIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BinaryField(max_length=1)),
            ],
        ),
    ]
