# Generated by Django 4.1.5 on 2023-02-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0025_emergencymodeindicator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencymodeindicator',
            name='enabled',
            field=models.BooleanField(),
        ),
    ]
