# Generated by Django 4.1.6 on 2023-02-26 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_alter_emergencymodeindicator_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_count', models.IntegerField()),
                ('timestamp_field', models.DateTimeField(auto_now_add=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.building')),
            ],
        ),
    ]
