# Generated by Django 4.1.6 on 2023-03-08 01:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_alter_devicecount_timestamp_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('count', models.PositiveSmallIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='building',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='building',
            name='start_time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='building',
            name='type',
            field=models.CharField(choices=[('Academic', 'Academic'), ('Apartment', 'Apartment'), ('Library', 'Library'), ('Sports Complex', 'Sports Complex'), ('Housing', 'Housing'), ('Student Services', 'Student Services'), ('Dining', 'Dining'), ('Administrative', 'Administrative'), ('Residence Hall', 'Residence Hall'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='devicecount',
            name='timestamp_field',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='emergencymodeindicator',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
